#!/bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

for i in $*
do
  NEWNAME=`basename $i .x`
  if [ "$i" != "$NEWNAME" ]; then
    NEWNAME=${NEWNAME}.sgi
    echo "converting $i"
    imconv $i -rgb $NEWNAME
  else
    echo "$i not an avs image file"
  fi
done

