#!/bin/sh
#BHEADER**********************************************************************
#
#  Copyright (c) 1995-2024, Lawrence Livermore National Security,
#  LLC. Produced at the Lawrence Livermore National Laboratory. Written
#  by the Parflow Team (see the CONTRIBUTORS file)
#  <parflow@lists.llnl.gov> CODE-OCEC-08-103. All rights reserved.
#
#  This file is part of Parflow. For details, see
#  http://www.llnl.gov/casc/parflow
#
#  Please read the COPYRIGHT file or Our Notice and the LICENSE file
#  for the GNU Lesser General Public License.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License (as published
#  by the Free Software Foundation) version 2.1 dated February 1999.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms
#  and conditions of the GNU General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  USA
#**********************************************************************EHEADER

Num=$1
shift
if [ $1 = "all" ]
then
	tests="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16"
else
	tests=$*
fi
for s in $Num
do
	getmc $s
	for i in $tests
	do
		if [ "$MALLOC_DEBUG" ]; then
			rm malloc.log.????
		fi
		echo "==================== test$i ===================="
		runt -p test$i 1
#		sleep 5
		runt -p test$i 5
#		sleep 5
		runt -p test$i 10
#		sleep 5
# 		runt -p test$i 100
#		sleep 5
		if [ "$MALLOC_DEBUG" ]; then
			echo "================== Not freed info =============="
			egrep -e "^known memory not freed" malloc.log.*
			egrep -e "^unknown memory not freed" malloc.log.*
			echo "================================================"
			cat malloc.log.* >> malloc.log.total
		fi
	done
	freemc
done

