#! /bin/sh
#BHEADER**********************************************************************
#
#  Copyright (c) 1995-2024, Lawrence Livermore National Security,
#  LLC. Produced at the Lawrence Livermore National Laboratory. Written
#  by the Parflow Team (see the CONTRIBUTORS file)
#  <parflow@lists.llnl.gov> CODE-OCEC-08-103. All rights reserved.
#
#  This file is part of Parflow. For details, see
#  http://www.llnl.gov/casc/parflow
#
#  Please read the COPYRIGHT file or Our Notice and the LICENSE file
#  for the GNU Lesser General Public License.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License (as published
#  by the Free Software Foundation) version 2.1 dated February 1999.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the IMPLIED WARRANTY OF
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the terms
#  and conditions of the GNU General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
#  USA
#**********************************************************************EHEADER

#=============================================================================
#
# Loop to parse users arguments
#
#=============================================================================
PROGRAM=""
while getopts hp: c
do
	case $c in
	hp) 
		echo "usage: $0 run runname process_group"
		echo "Runs parflow on the allocated cube."
	        exit 0;;
	p) 
	       PROGRAM=$2
	       shift 
	       shift;;
esac
done

if [ "$MALLOC_DEBUG" ]; then
	rm -f malloc.log.????
fi

#
# The following is a hack to deal with NFS temp mount problems
#
if [ -z "$AMPS_ROOT_DIR" ]; then
	AMPS_ROOT_DIR=$HOME
	export AMPS_ROOT_DIR
fi

real_home=`(cd $AMPS_ROOT_DIR; sh -c "pwd")`
AMPS_EXE_DIR=`echo \`pwd\` | sed "s#$real_home#$AMPS_ROOT_DIR#"`
export AMPS_EXE_DIR

if [ -z "$PROGRAM" ]
then
	#
	# The default is to run ParFlow
	#
	PROGRAM=parflow
	pfstrip $1.in.solver $1.in.solver.strp
	pfstrip $1.in.problem $1.in.problem.strp

fi

#mpirun -arch sun4 -np 5 -arch IRIX -np 2 /home/steve/parflow/src/parflow/$PROGRAM.mpi1.%a $* 
#mpirun -arch sun4 -np 1 -arch LINUX -np 1 /home/steve/parflow/src/parflow/$PROGRAM.mpi1.%a $* 
#mpirun -arch sun4 -np 4 -arch LINUX -np 1 /home/steve/parflow/src/parflow/$PROGRAM.mpi1.%a $* 
mpirun -arch CRAY -np `cat .amps.info.` $PROGRAM.mpi1.CRAY $* 


if [ "$MALLOC_DEBUG" ]; then
	grep "^known" malloc.log.* 
fi



