#! /bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

echo "#QSUB -l mpp_p=$1,mpp_t=4:00:00\n"\
"cd `pwd`\n"\
"setenv PVM_MAX_PACK 100000+50000\n"\
"getmc $1 $2\n"\
"run $2 $2\n"\
"freemc $2" | qsub





