#!/bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

#=============================================================================
#
# Loop to parse users arguments
#
#=============================================================================
PROGRAM=""
while getopts hp: c
do
	case $c in
	hp) 
		echo "usage: $0 run runname process_group"
		echo "Runs parflow on the allocated cube."
	        exit 0;;
	p) 
	       PROGRAM=$2
	       shift 
	       shift;;
esac
done

if [ "$MALLOC_DEBUG" ]; then
	rm -f malloc.log.????
fi

if [ -z "$PROGRAM" ]
then
	#
	# The default is to run ParFlow
	#
	PROGRAM=parflow
fi

$PARFLOW_DIR/bin/$PROGRAM $1 >& $1.out.txt
echo done
if [ -f ./malloc.log.0000 ]; then
	grep "^known" malloc.log.* 
fi



