/* config.h.  Generated by configure.  */
/* config.hin.  Generated from configure.ac by autoheader.  */

/* FCMIX: Define name-mangling macro */
#define F77_FUNC(name,NAME) name ## _

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the <math.h> header file. */
#define HAVE_MATH_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "radu@llnl.gov"

/* Define to the full name of this package. */
#define PACKAGE_NAME "SUNDIALS"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "SUNDIALS 2.2.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "sundials"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.2.0"

/* The size of a `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of a `float', as computed by sizeof. */
/* #undef SIZEOF_FLOAT */

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long double', as computed by sizeof. */
/* #undef SIZEOF_LONG_DOUBLE */

/* The size of a `long int', as computed by sizeof. */
#define SIZEOF_LONG_INT 4

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* FCMIX: Make function names lowercase */
/* #undef SUNDIALS_CASE_LOWER */

/* FCMIX: Make function names uppercase */
/* #undef SUNDIALS_CASE_UPPER */

/* Define SUNDIALS data type 'realtype' as 'double' */
#define SUNDIALS_DOUBLE_PRECISION 1

/* Define SUNDIALS data type 'realtype' as 'long double' */
/* #undef SUNDIALS_EXTENDED_PRECISION */

/* FNVECTOR: Allow user to specify different MPI communicator */
#define SUNDIALS_MPI_COMM_F2C 1

/* Define SUNDIALS data type 'realtype' as 'float' */
/* #undef SUNDIALS_SINGLE_PRECISION */

/* FCMIX: Do NOT append any underscores to functions names */
/* #undef SUNDIALS_UNDERSCORE_NONE */

/* FCMIX: Append ONE underscore to function names */
/* #undef SUNDIALS_UNDERSCORE_ONE */

/* FCMIX: Append TWO underscores to function names */
/* #undef SUNDIALS_UNDERSCORE_TWO */

/* Use generic math functions */
#define SUNDIALS_USE_GENERIC_MATH 1
