#! /bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

HOST_FILE="./.hostfile"
HOST_FILE_PVM="./.hostfile.pvm"
OPTS=""

if [ $1 = "-h" ]
then
       echo "usage: $0 number_nodes [host_file]"
       echo "Starts the PVMD."
       echo "<number_nodes> is ignored for PVM"
       echo "Machines to run on are specified in the host_file."
       echo "host_file defaults to <$HOST_FILE>"
       exit 0
fi

if [ ! "$2" ]
then
	if [ ! -f $HOST_FILE ]
	then
		echo "error: either specify a host file or create <$HOST_FILE>"
		exit 1
	fi
else
	HOST_FILE=$2
	if [ ! -f $HOST_FILE ]
	then
		echo "error: the host file <$HOST_FILE> does not exist"
		exit 1
	fi
fi

rm -f $HOST_FILE_PVM
for i in `cat $HOST_FILE`
do
	echo ${i} >> $HOST_FILE_PVM
done

echo $1 > .amps.pvm.bootmc

pvmd  $HOST_FILE &
