#! /bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

if [ $# -gt 1 ]
then
       echo "usage: $0"
       echo "Kills the booted multicomputer."
       echo "Kills the PVMD process."
       exit 0
fi

echo "halt" | pvm > /dev/null


