#! /bin/sh 
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

#=============================================================================
#
# This Script builds the parflow/avs module libraries and installs them.
#
#=============================================================================

#=============================================================================
#
# Set up directory locations
#
#=============================================================================
if [ -z "$PARFLOW_SRC" ]
then
        PARFLOW_SRC=$PARFLOW_DIR
fi

#=============================================================================
#
# Determine the arch that we are compiling on 
#
#=============================================================================
. $PARFLOW_SRC/config/getarch

#=============================================================================
#
# Parse the user arguments
#
#=============================================================================
. $PARFLOW_SRC/config/parse_build_args.sh

if [ -z "$PFAVS_PATH" ]
then
	echo "AVS not supported"
	exit 0
fi

#=============================================================================
#
# If on a new arch then clean everything
#
#=============================================================================
if [ "$PF_ARCH" != "$PF_OLD_ARCH" ]
then
	$PFAVS_MAKE veryclean
fi


#=============================================================================
#
# Do the actual make 
#
#=============================================================================
if [ "$PF_ALL_FLAG" ]
then
	#======================================================================
	# If we have the image tool library installed then 
	# make the modules that depend on it
	#======================================================================
	if [ -z "$PFAVS_IMAGE_TOOLS_INCLUDE_PATH" ]
	then
		echo "No Image Tools"
		PFAVS_IMAGE_TOOLS_DEPEND_SRC=
		PFAVS_IMAGE_TOOLS_LIBS="../../tools/tools_io.o"
		PFFLAGS="$PFAVS_DEF"
	else
		echo "With Image Tools"
		PFAVS_IMAGE_TOOLS_DEPEND_SRC="WRITE_ANY_IMAGE.c"
		PFAVS_IMAGE_TOOLS_LIBS="-lim -lsdsc ../../tools/tools_io.o"
		PFFLAGS="-DIMAGE_TOOLS $PFAVS_DEF"
	fi

	export PFAVS_IMAGE_TOOLS_DEPEND_SRC PFAVS_IMAGE_TOOLS_LIBS PFFLAGS

	#======================================================================
	#
	# Build the module library.
	#
	#======================================================================

	echo "Building"
	echo "  CC:       $PF_AVSCC"
	echo "  PF_ARCH:  $PF_ARCH"
	echo ""

	$PFAVS_MAKE
fi




#=============================================================================
#
# Do the install
# 
#=============================================================================
if [ "$PF_INSTALL_FLAG" ] 
then
	PARFLOW_BIN=$PARFLOW_DIR/bin
 
	if [ ! -d $PARFLOW_BIN ]
 	then
	        mkdir $PARFLOW_BIN
	fi

	UTILITIES="pfavs"

	(cd $PARFLOW_BIN
	for i in $UTILITIES
	do
		rm -f $i
		$PF_INSTALL $PARFLOW_SRC/avs/modules/$i $i
	done)

	#======================================================================
	#
	# Install the AVS executables
	#
	#======================================================================
	if [ ! -d $PARFLOW_DIR/avs ]
	then
		mkdir $PARFLOW_DIR/avs
	fi

	if [ ! -d $PARFLOW_DIR/avs/mod_lib ]
	then
		mkdir $PARFLOW_DIR/avs/mod_lib
	fi

	MODULES="ParFlow pf_modules rotate_geometry"
	(cd $PARFLOW_DIR/avs/mod_lib
	for i in $MODULES
	do
		rm -f $i
		$PF_INSTALL $PARFLOW_SRC/avs/modules/$i $i
	done)

	#======================================================================
	#
	# Install the AVS help files
	#
	#======================================================================

	if [ ! -d $PARFLOW_DIR/avs/help ]
	then
		mkdir $PARFLOW_DIR/avs/help
	fi

	FILES=`(cd $PARFLOW_SRC/avs/modules; ls *.txt)`
	(cd $PARFLOW_DIR/avs/help
	for i in $FILES
	do
		rm -f $i
		$PF_INSTALL $PARFLOW_SRC/avs/modules/$i $i
	done
	avs -reindex .)

	#======================================================================
	#
	# Install the AVS networks
	#
	#======================================================================
	if [ "$PARFLOW_DIR" != "$PARFLOW_SRC" ]
	then
		if [ ! -d $PARFLOW_DIR/avs/networks ]
		then
			mkdir $PARFLOW_DIR/avs/networks
		fi

		FILES=`(cd $PARFLOW_SRC/avs/networks; ls *.net)`
		(cd $PARFLOW_DIR/avs/networks
		for i in $FILES
		do
			rm -f $i
			$PF_INSTALL $PARFLOW_SRC/avs/networks/$i $i
		done)
	fi
fi

#=============================================================================
#
# Clean.
#
#=============================================================================
if [ "$PF_CLEAN_FLAG" ]
then
    rm .current_arch
    $PFAVS_MAKE clean
fi

if [ "$PF_VERYCLEAN_FLAG" ]
then
    $PFAVS_MAKE veryclean
fi




