#!/bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

#=============================================================================
#
# Runs AVS.
# 
# Links to the AVS binaries based on the architecture of the machine
# we are running on.
#
#=============================================================================

#=============================================================================
#
# If user has not specified parflow directory then assume that we are
# in it and check this assumption.
#
#=============================================================================

OLD_DIR=`pwd`
if [ ! "$PARFLOW_DIR" ]; then
    cd ..
    PARFLOW_DIR=`pwd` 
    export PARFLOW_DIR
    cd $OLD_DIR
    if [ ! -d $PARFLOW_DIR/avs ]
    then
	echo  "Error: set the PARFLOW_DIR environment variable"
        exit 1
    fi
fi

#=============================================================================
#
# Determine which machine we are running on so we can link the 
# correct ParFlow libraries
#
#=============================================================================

$AVS_PATH/bin/avs \
	-data   `pwd` \
	-netdir $PARFLOW_DIR/avs/networks \
	-library $AVS_PATH/unsupp_mods/Unsupported \
	-library $AVS_PATH/chem_lib/Chemistry \
	-library $AVS_PATH/avs_library/Animation \
	-library $AVS_PATH/avs_library/Supported \
	-library $PARFLOW_DIR/avs/mod_lib/ParFlow \
	  $*
