#!/bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

#=============================================================================
#
#	This Script builds ParFlow.
#
# This script is normally invoke by XParFlow but users are free to
# invoke it directly if they wish.
#
# Assumes that we have a "normal" parflow directory structure and that
# build script is invoked in the exe directory.  
#
#	parflow ----> exe
#	         |
#                |--> src  
# 
# By the setting PARFLOW_DIR environment variable to the location of
# the parflow directory you can compile source in another location.
# (IE if you want to create a test program and link to AMPS layer).
#
# This file is architecture/communications package independent and
# should remain that way.
#
#=============================================================================

#=============================================================================
#
# Initialize Variables
#
#=============================================================================
# Default program name
PF_PROGRAM="parflow"
export PF_PROGRAM

PF_CC_OPTS=""
PF_MAKE_OPTS=""

if [ ! "$PARFLOW_DIR" ]; then
  echo "Error: set the PARFLOW_DIR environment variable"
  exit 1
fi

#=============================================================================
#
# Set up directory locations
#
#=============================================================================
if [ -z "$PARFLOW_SRC" ]
then
        PARFLOW_SRC=$PARFLOW_DIR
fi

#=============================================================================
#
# build script is executed in exe directory so cd over to where
# source is at.
#
#=============================================================================
cd $PARFLOW_SRC/parflow

#=============================================================================
#
# Determine the arch that we are compiling on 
#
#=============================================================================
. $PARFLOW_SRC/config/getarch

args=$*

#=============================================================================
#
# Parse the user arguments
#
#=============================================================================
. $PARFLOW_SRC/config/parse_build_args.sh

PARFLOW_BIN=$PARFLOW_DIR/bin
 
if [ ! -d $PARFLOW_BIN ]
then
        mkdir $PARFLOW_BIN
fi

CFLAGS="$PF_NODE_DEF -I$PARFLOW_SRC/config"
LFLAGS=$PF_NODE_LINK_DEF
FFLAGS=$PF_NODE_F77_DEF
if [ "$PF_OPTIMIZE_FLAG" ]
then
	CFLAGS="$CFLAGS $PF_NODE_OPT"
        FFLAGS="$FFLAGS $PF_NODE_F77_OPT"
        LFLAGS="$LFLAGS $PF_NODE_LINK_OPT"
fi
 
if [ "$PF_DEBUG_FLAG" ]
then
        CFLAGS="$CFLAGS $PF_NODE_DEBUG"
        FFLAGS="$FFLAGS $PF_NODE_F77_DEBUG"
        LFLAGS="$LFLAGS $PF_NODE_LINK_DEBUG"
fi

if [ "$PF_PROFILE_FLAG" ]
then
        CFLAGS="$CFLAGS $PF_NODE_PROF"
        FFLAGS="$FFLAGS $PF_NODE_F77_PROF"
        LFLAGS="$LFLAGS $PF_NODE_LINK_PROF"
fi

if [ "$PF_TIMING_FLAG" ]
then
       CFLAGS="$CFLAGS $PF_NODE_TIMING"
       FFLAGS="$FFLAGS $PF_NODE_F77_TIMING"
       LFLAGS="$LFLAGS $PF_NODE_LINK_TIMING"
fi
export CFLAGS FFLAGS LFLAGS

#=============================================================================
#
# Echo things back to the user so they know what they are doing.
#
#=============================================================================
echo "Building"
echo "       Program:                $PF_PROGRAM"
echo "       Arch:                   $PF_ARCH"
echo "       Cluster:                $CLUSTER"
echo "       Communications package: $PF_COMM"
echo "       CC Options:             $CFLAGS"
echo "       F77 Options:            $FFLAGS"
echo "       Make Options:           $PF_MAKE_OPTS"

#=============================================================================
# Invoke the communications package specific script.
# Each communications package has its own special one.
# We source it so it inherits all variables.
#=============================================================================
#echo "SGS"
#printenv > ~/parflow.env
. $PARFLOW_SRC/amps/$PF_COMM/build.program $args

echo "done"
exit 0



