#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

include $(PARFLOW_SRC)/amps/$(PF_COMM)/Makefile.$(PF_ARCH).mptopf

all: $(PF_PROGRAM)$(PF_EXT)

PF_SRC= $(PF_PROGRAM).c

include $(PARFLOW_SRC)/amps/$(PF_COMM)/Makefile.$(PF_ARCH).pftomp

