#!/bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

#=============================================================================
#
#	This Script attempts to determine the architecture and
#	communications package to use.
#
# Script is invoked by the build script.
#
#=============================================================================

#
# Determine the architecture
#

#
# First try uname 
#
PF_OS="`uname -s`"
PF_OS_Release="`uname -r`"
PF_OS_Machine="`uname -m`"

#
# Based on what we found from system queries set PF_ARCH
#
if [ -z "$PF_ARCH" ]
then
	case "$PF_OS" in
		Linux) 
                       PF_ARCH="linux"
                       SUNDIALS_ARCH=`uname -s`.`uname -m`;;
		AIX)   PF_ARCH="sp2";;
		Darwin)	PF_ARCH="darwin";;
	esac
fi

#
# Default MP system for the architecture we determined above
#
if [ -z "$PF_COMM" ]
then
	case "$PF_ARCH" in
		linux) PF_COMM="mpi1";;
		darwin) PF_COMM="mpi1";;
	esac
fi

export PF_ARCH PF_COMM SUNDIALS_ARCH
