set(AMPS_SRC_FILES
  amps_allreduce.c
  amps_bcast.c
  amps_createinvoice.c
  amps_exchange.c
  amps_ffopen.c
  amps_finalize.c
  amps_fopen.c
  amps_init.c
  amps_io.c
  amps_irecv.c
  amps_newpackage.c
  amps_pack.c
  amps_recv.c
  amps_send.c
  amps_sizeofinvoice.c
  amps_sync.c
  amps_test.c
  amps_unpack.c
  amps_vector.c
  amps_wait.c
  drand48.c
  erand48.c
  jrand48.c
  lrand48.c
  mrand48.c
  nrand48.c
  _rand48.c
  srand48.c
  unix_port.c
  )
