#! /bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

if [ $1 = "-h" ]
then
       echo "usage: $0 number_nodes"
       echo "Allocates the number of nodes specified."
       exit 0
fi

echo $1 > .amps.info.$2

