#! /bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

if [ $# -gt 0 ]
then
       echo "usage: $0"
       echo "Returns information on current PVM machine"
       exit 0
fi


if [ "AIX" = "`uname`" ]
then
    #
    # IBM SP2 
    #
    pstat
    exit 0
fi

if [ "OSF1" = "`uname`" ]
then
    #
    # DEC 
    #
    pstat
    exit 0
fi

echo "Not Implemented"
