#! /bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

HOST_FILE="./.hostfile"
OPTS=""

if [ $1 = "-h" ]
then
       echo "usage: $0 number_nodes"
       exit 0
fi

echo $1 > .amps.smpi.bootmc

if [ "AIX" = "`uname`" ]
then
    #
    # IBM SP2
    #
  
    exit 0
fi

if [ "`mpirun 2> /dev/null`" = "Missing: program name" ] 
then
    #
    # MPICH
    # 
    echo 
else
    #
    # LAM
    # 
    lamboot -v .hostfile
    echo 
fi

exit 0

