#!/bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.1.1.1 $
#EHEADER***********************************************************************

#=============================================================================
#
#	This Script attempts to determine the architecture and
#	communications package to use.
#
# Script is invoked by the build script.
#
#=============================================================================

PF_OS=""

#
# Determine the architecture
#
if [ ! "$PF_ARCH" ]; then
	
	#
	# First try uname 
	#
	if [ -f /bin/uname ] 
	then
		PF_OS="`/bin/uname -s`"
		PF_OS_Release="`/bin/uname -r`"
	fi

	#
	# Based on what we found from system queries set PF_ARCH
	#
	case "$PF_OS" in
		SunOS) case "$PF_OS_Release" in	
				4.1.3) PF_ARCH="sunos";;
				5.4)   PF_ARCH="solaris";;
			esac;;
		Linux) PF_ARCH="linux";;
		AIX)   PF_ARCH="sp1";;
		sn*)   PF_ARCH="pvmi";;
		IRIX)	PF_ARCH="irix";;
	esac

	if [ -d /usr/ncube ]; then
		PF_ARCH="ncube2"
	fi
fi

#
# Default MP system for the architecture we determined above
#
if [ ! "$PF_COMM" ]; then
	case "$PF_ARCH" in
		sunos) PF_COMM="cerk";;
		solaris) PF_COMM="pvms";;
		linux) PF_COMM="pvms";;
		ncube2) PF_COMM="cerk";;
		sp1) PF_COMM="chameleon";;
		pvmi) PF_COMM="t3ds";;
		irix) PF_COMM="irixshmem";;
	esac
fi

