#! /bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.32 $
#EHEADER***********************************************************************

#=============================================================================
#
# Set up directory locations
#
#=============================================================================
if [ -z "$PARFLOW_SRC" ]
then
        PARFLOW_SRC=$PARFLOW_DIR
fi

#=============================================================================
#
# Determine the arch that we are compiling on 
#
#=============================================================================
. $PARFLOW_SRC/config/getarch

#=============================================================================
#
# Parse the user arguments
#
#=============================================================================
. $PARFLOW_SRC/config/parse_build_args.sh

#=============================================================================
#
# If on a new arch then clean everything
#
#=============================================================================
if [ "$PF_ARCH" != "$PF_OLD_ARCH" ]
then
	$PFTOOLS_MAKE veryclean
	$PFTOOLS_MAKE -f Makefile.tcllib veryclean
fi

#=============================================================================
#
# Do the actual make 
#
#=============================================================================


if [ "$PF_ALL_FLAG" ]
then

        CFLAGS="$PFTOOLS_DEF"
        if [ "$PF_OPTIMIZE_FLAG" ]
        then
                CFLAGS="$CFLAGS $PFTOOLS_OPT"
        fi
 
        if [ "$PF_DEBUG_FLAG" ]
        then
                CFLAGS="$CFLAGS $PFTOOLS_DEBUG"
        fi

        if [ "$PF_PROFILE_FLAG" ]
        then
                CFLAGS="$CFLAGS $PFTOOLS_PROF"
        fi
        export CFLAGS

	$PFTOOLS_MAKE
	$PFTOOLS_MAKE -f Makefile.tcllib  
fi

#=============================================================================
#
# Do the install
# 
#=============================================================================
if [ "$PF_INSTALL_FLAG" ] 
then
	PARFLOW_BIN=$PARFLOW_DIR/bin
 
	if [ ! -d $PARFLOW_BIN ]
	then
	        mkdir $PARFLOW_BIN
	fi
	#=====================================================================
	#
	# Install the executables and scripts
	#
	#=====================================================================
	UTILITIES="parflow$PFTOOLS_SHLIB_SUFFIX pfhelp pfmvio pfbtosa pfsbtosa pfstrip pfwell_cat pfwell_data gmssol2pfsol gmstinvertices bgmsfem2pfsol gmstriangulate projecttin"

	(cd $PARFLOW_BIN
	for i in $UTILITIES
	do
		rm -f $i
		$PF_INSTALL $PARFLOW_SRC/tools/$i $i
	done)

	#======================================================================
	#
	# Install the main shell scripts
	#
	#======================================================================
	UTILITIES="gmsfem2pfsol xpftools pfco"
	(cd $PARFLOW_BIN
	for i in $UTILITIES
	do
		rm -f $i
		$PF_INSTALL $PARFLOW_SRC/tools/$i.sh $i
	done)

	#======================================================================
	#
	# Install the main TCL scripts
	#
	#======================================================================
	UTILITIES="pflocked pfwrite tkdiff xpfci xpfmpeg xparflow"
	(cd $PARFLOW_BIN
	for i in $UTILITIES
	do
		rm -f $i
		$PF_INSTALL $PARFLOW_SRC/tools/$i.tcl $i
	done)

	#======================================================================
	#
	# Install the support TCL scripts
	#
	#======================================================================
	UTILITIES="dirt evap fsb fsbox metaEListBox metaEntry pftformat winsync xpftdatadsp xpftdiffdsp xpftfunctions xpftfuncwin xpftgeneral xpftgriddsp xpfthelp xpftinfowin xpftnewgrid xpftpf xpftsds xpftstatdsp xpftools pkgIndex parflow pfvtk xpfthreeslices"

	(cd $PARFLOW_BIN
	for i in $UTILITIES
	do
		rm -f $i.tcl
		$PF_INSTALL $PARFLOW_SRC/tools/$i.tcl $i.tcl
	done)

	#======================================================================
	#
	# Install the bitmaps
	#
	#======================================================================
	UTILITIES="down info pgup xpft elistarrow pgdown up"
	(cd $PARFLOW_BIN	
	for i in $UTILITIES
	do
		rm -f $i.xbm
		$PF_INSTALL $PARFLOW_SRC/tools/$i.xbm $i.xbm
	done)

	#======================================================================
	#
	# Install the misc support scripts
	#
	#======================================================================
	UTILITIES="xpfmpeg.param xpftools.opt"
	(cd $PARFLOW_BIN	
	for i in $UTILITIES
	do
		rm -f $i
		$PF_INSTALL $PARFLOW_SRC/tools/$i $i
	done)
fi


#=============================================================================
#
# Clean the local directory
#
#=============================================================================
if [ "$PF_CLEAN_FLAG" ]
then
	$PFTOOLS_MAKE clean
	$PFTOOLS_MAKE -f Makefile.tcllib clean
fi

if [ "$PF_VERYCLEAN_FLAG" ]
then
	$PFTOOLS_MAKE veryclean
	$PFTOOLS_MAKE -f Makefile.tcllib veryclean
fi








