#!/bin/sh
#BHEADER***********************************************************************
# (c) 1995   The Regents of the University of California
#
# See the file COPYRIGHT_and_DISCLAIMER for a complete copyright
# notice, contact person, and disclaimer.
#
# $Revision: 1.2 $
#EHEADER***********************************************************************

awk '!/(^#)|(^[\ ]*$)/ {print}' < $1 > $2
